# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('univ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name_cached', models.CharField(blank=True, max_length=30)),
                ('is_addition', models.BooleanField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_logs', to='univ.School')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='univ.Tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
