# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0002_taglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name_cached',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='name_cached',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
