# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20160920_2303'),
        ('univ', '0006_auto_20160920_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNUInWorld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('redirect', models.BooleanField(default=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wiki.Page')),
            ],
            options={
                'verbose_name_plural': 'SNU in World',
                'verbose_name': 'SNU in World',
            },
        ),
    ]
