# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 10:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='page_title_for_url',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='essay',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_for_url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pagerevision',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[^_/]+\\Z', 32), message="Title cannot contain '_' or '/'.")]),
        ),
    ]
