# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20160920_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=models.TextField(max_length=1000000),
        ),
    ]
