# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 07:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title_for_url', models.CharField(blank=True, max_length=257)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=65535)),
                ('creator_name', models.CharField(blank=True, max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_essays', to=settings.AUTH_USER_MODEL)),
                ('likers', models.ManyToManyField(related_name='liked_essays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.PositiveIntegerField(null=True, verbose_name='sub id')),
                ('title_for_url', models.CharField(max_length=257)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveSmallIntegerField(editable=False, null=True)),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[^_/]+\\Z', 32), message="Title cannot contain '_' or '/'.")])),
                ('content', models.TextField(blank=True, max_length=65535)),
                ('editor_name', models.CharField(blank=True, max_length=30)),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('edit_summary', models.CharField(max_length=255)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_pages', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wiki.Page')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wiki.PageRevision')),
            ],
            options={
                'get_latest_by': 'edited',
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ko', 'Korean'), ('en', 'English')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wiki.PageRevision'),
        ),
        migrations.AddField(
            model_name='page',
            name='wiki',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wiki.Wiki'),
        ),
        migrations.AddField(
            model_name='essay',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays', to='wiki.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='pagerevision',
            unique_together=set([('page', 'revision_number')]),
        ),
        migrations.AlterIndexTogether(
            name='pagerevision',
            index_together=set([('page', 'revision_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('wiki', 'subid')]),
        ),
        migrations.AlterIndexTogether(
            name='page',
            index_together=set([('wiki', 'subid')]),
        ),
    ]
