# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20160802_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
