# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-10 06:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20160930_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerevision',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_revisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
