# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20161010_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='External',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WP', 'Wikipedia'), ('NW', 'Namu Wiki')], max_length=2)),
                ('url', models.URLField()),
                ('ccl', models.BooleanField(default=False, verbose_name='CCL compatible')),
                ('preview', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='wiki',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='wiki.Wiki'),
        ),
        migrations.AddField(
            model_name='external',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externals', to='wiki.Page'),
        ),
    ]
