# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0004_country_flag_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, upload_to='univ/school/logo/'),
        ),
        migrations.AddField(
            model_name='school',
            name='schltype',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
