# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-01 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import globalsnu.univ.models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0008_auto_20161015_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, upload_to=globalsnu.univ.models.School.upload_directory_path),
        ),
    ]
